---

## ansible configuration
ansible_user: vagrant
ansible_ssh_common_args: "-F {{ playbook_vagrant_path }}/{{ playbook_vagrant_alias }}/ssh_config"

## do not use a specific host name
playbook_front_server_name: "{{ inventory_hostname }}"

## igloo-ansible-playbooks configuration
playbook_is_vagrant_host: true
playbook_environment: development
playbook_remote_user: tomcat
## prevent uid clash for ubuntu vm
playbook_remote_user_uid: 4000
playbook_ssl_selfsigned_certs: true

## dev_hosts registration
dh_hostnames:
  - '@self'
