---

##
## install packages needed for client-side ansible
##

- hosts: "{{ common_hosts }}"
  pre_tasks:
    - name: maven_artifact requisites
      package:
        name: "{{ 'python3-lxml' if ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8' else 'python-lxml' }}"
      become: true
      become_user: root

  roles:
    - role: powo.utils
    # TODO: handle become at role level
    - role: utils
      become: true
      become_user: root
    # TODO: drop selinux role and variables
    # https://github.com/ansible/ansible/issues/16612
    - role: selinux
      selinux_handle: 'auto'
      become: true
      become_user: root
