---

- hosts: "{{ common_hosts }}"
  roles:

    - role: config
      config_name: "{{ playbook_application_name }}"
      config_user: "{{ playbook_remote_user }}"
      config_group: "{{ playbook_remote_user }}"
      config_properties: "{{ playbook_config_properties }}"
      become: true
      become_user: root
      tags: config

    - role: war
      war_application_war_src: "{{ playbook_war }}"
      war_application_war_remote_src: "{{ playbook_war_remote_src | default(False) }}"
      war_application_user: "{{ playbook_remote_user }}"
      war_tomcat_service: "tomcat@{{ playbook_application_name }}"
      war_tomcat_catalina_base: "{{ playbook_application_tomcat_path }}"
      war_context_name: "{{ playbook_context_name }}"
      become: true
      become_user: root
      tags: deploy-war
    
    - role: deb_delivery
      # file list of .deb files to copy and install
      # a sudo rule must exists to allow .deb installation
      # playbook_sudoers_deb must be true and sudoers provisioned
      #delivery_deb_files: []
      tags: deploy-war
