---

- hosts: "{{ common_hosts }}"
  roles:

    - role: config
      config_name: "{{ playbook_application_name }}"
      config_user: "{{ playbook_remote_user }}"
      config_group: "{{ playbook_remote_user }}"
      config_properties: "{{ playbook_config_properties }}"
      become: true
      become_user: root

    - role: war
      war_application_war_src: "{{ playbook_local_git_project }}/{{ playbook_maven_folder }}{{ playbook_local_git_war_path }}"
      war_application_war_remote_src: no
      war_application_user: "{{ playbook_remote_user }}"
      war_tomcat_service: "tomcat@{{ playbook_application_name }}"
      war_tomcat_catalina_base: "{{ playbook_application_tomcat_path }}"
      war_context_name: "{{ playbook_context_name }}"
      become: true
      become_user: root
