---

##
## install java / postgresql / tomcat stack
##

- hosts: "{{ common_hosts }}"
  pre_tasks:

    - block:

      # TODO: organize this step after httpd install ?
      - name: /etc/httpd/certs
        file:
          path: /etc/httpd/certs
          state: directory
          owner: root
          group: root
          mode: u=rwx,g=,o=

      - name: group
        group:
          name: "{{ playbook_remote_user }}"
          gid: 3000

      - name: user create
        user:
          name: "{{ playbook_remote_user }}"
          uid: 3000
          createhome: yes

      - name: user groups
        user:
          name: "{{ playbook_remote_user }}"
          groups: "users,{{ playbook_remote_user }}"
          append: yes

      become: true
      become_user: root

  roles:
    - role: firewall
      become: true
      become_user: root
      tags: firewall
      when: playbook_firewall_managed | default(True)

    - role: httpd
      httpd_step_install: yes
      httpd_step_configuration: no
      become: true
      become_user: root
      tags: httpd

    - role: postgresql
      become: true
      become_user: root
      postgresql_versions:
        - "{{ playbook_postgresql_version }}"
      tags: postgresql

    - role: filesystem
      filesystem_application_name: "{{ playbook_application_name }}"
      filesystem_application_user: "{{ playbook_remote_user }}"
      filesystem_application_folders: "{{ playbook_application_folders }}"
      tags: filesystem

    - role: java
      become: true
      become_user: root
      java_download_path: /data/work
      java_runtime_path: /data/opt
      java_results_var: jdks
      java_runtimes: "{{ playbook_java_runtimes }}"
      tags:
        - java
        - tomcat

    - role: ssl_selfsigned
      become: true
      become_user: root
      ssl_selfsigned_cn: "{{ playbook_front_server_name }}"
      ssl_selfsigned_aliases: []
      ssl_selfsigned_certificate: "{{ playbook_ssl_certificate }}"
      ssl_selfsigned_key: "{{ playbook_ssl_key }}"
      when: playbook_ssl_selfsigned_certs
      tags: httpd

    - role: httpd
      become: true
      become_user: root
      httpd_server_name: "{{ playbook_front_server_name }}"
      httpd_server_aliases: []
      httpd_application_name: "{{ playbook_application_name }}"
      httpd_documentroot: "{{ playbook_application_path }}/site"
      httpd_ssl_certificate: "{{ playbook_httpd_ssl_certificate }}"
      httpd_ssl_key: "{{ playbook_httpd_ssl_key }}"
      httpd_ssl_cacertificate: "{{ playbook_httpd_ssl_cacertificate }}"
      httpd_context_name: "{{ playbook_context_name }}"
      httpd_ajp_port: "{{ playbook_tomcat_ajp_port }}"
      httpd_manage_vhost_configuration: "{{ playbook_httpd_manage_vhost_configuration }}"
      tags: httpd

    - role: postgresql_cluster
      become: true
      become_user: root
      postgresql_cluster_clusters:
        - name: "{{ playbook_postgresql_service_suffix }}"
          path: /data/services/pgsql/{{ playbook_postgresql_version }}/data
          postgresql_version: "{{ playbook_postgresql_version }}"
          port: "{{ playbook_postgresql_port }}"
          databases:
            - name: "{{ playbook_postgresql_database }}"
              owner: "{{ playbook_postgresql_user }}"
              schemas:
                - "{{ playbook_postgresql_user }}"
          users:
            - username: "{{ playbook_postgresql_user }}"
              password: "{{ playbook_postgresql_password }}"
              databases:
                - name: "{{ playbook_postgresql_database }}"
                  privileges: CONNECT,CREATE
      tags: postgresql

    - role: glowroot_agent
      glowroot_agent_version: "{{ playbook_glowroot_agent_version }}"
      glowroot_agent_download_target_path: "{{ playbook_glowroot_agent_download_target_path }}"
      glowroot_agent_install_target_path: "{{ playbook_glowroot_agent_install_target_path }}"
      glowroot_config_agent_id: "{{ playbook_glowroot_config_agent_id }}"
      # process running glowroot perform following actions in glowroot dir :
      # - writes config.json
      # - writes in tmp dir
      # - read glowroot.properties file
      glowroot_agent_user: "{{ playbook_remote_user }}"
      glowroot_agent_group: "{{ playbook_remote_user }}"
      glowroot_config_collector_address: "{{ playbook_glowroot_config_collector_address }}"
      glowroot_config_log_dir: "{{ playbook_glowroot_config_log_dir }}"

      tags: glowroot
      when: playbook_glowroot_enabled

    - role: tomcat
      become: true
      become_user: root
      tomcat_version: 9.0.10
      tomcat_checksum: sha512:ecdee920fcb75bf30cd87c350e0732e8fa566911cd16cf2759689edd324ebac911c0d154e79ffc67e948b29eacc49c88dadc5954383d3c4af2fdb952f3d1c371
      tomcat_dest: /data/opt/tomcat-9.0.10
      tomcat_default_user: "{{ playbook_remote_user }}"
      tomcat_default_java_home: "{{ jdks[playbook_java_key].path }}"
      tomcat_timeout_stop: 30s
      tomcat_download_target_path: "{{ playbook_download_target_path }}"
      tomcat_default_extra_opts: >-
        {{ ('-javaagent:' + playbook_glowroot_jar) if playbook_glowroot_enabled else '' }}
        {{ ('-Digloo.profile=' + playbook_igloo_profile) if playbook_igloo_profile is defined and playbook_igloo_profile else none }}
      tomcat_catalina_bases:
        - name: "{{ playbook_application_name }}"
          path: "{{ playbook_application_tomcat_path }}"
          apj_port: "{{ playbook_tomcat_ajp_port }}"
          http_port: "{{ playbook_tomcat_http_port }}"
          ajp_max_threads: "{{ playbook_tomcat_ajp_max_threads }}"
          http_max_threads: "{{ playbook_tomcat_http_max_threads }}"
          shutdown_port: "{{ playbook_tomcat_shutdown_port }}"
          xmx: "{{ playbook_tomcat_xmx }}"
          xms: "{{ playbook_tomcat_xms }}"
      tags: tomcat
