---

##
## install java / postgresql / tomcat stack
##

- hosts: "{{ common_hosts }}"
  pre_tasks:
    # TODO: organize this step after httpd install ?
    - name: /etc/httpd/certs
      file:
        path: /etc/httpd/certs
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=,o=
      become: true
      become_user: root
  roles:
    - role: httpd
      httpd_step_install: yes
      httpd_step_configuration: no
      become: true
      become_user: root

    - role: postgresql
      become: true
      become_user: root
      postgresql_versions:
        - "9.6"

    - role: filesystem
      filesystem_application_name: "{{ playbook_application_name }}"
      filesystem_application_user: "{{ playbook_remote_user }}"
      filesystem_application_folders: "{{ playbook_application_folders }}"

    - role: java
      become: true
      become_user: root
      java_download_path: /data/work
      java_runtime_path: /data/opt
      java_results_var: jdks
      java_runtimes: "{{ playbook_java_runtimes }}"

    - role: ssl_selfsigned
      become: true
      become_user: root
      ssl_selfsigned_cn: "{{ playbook_front_server_name }}"
      ssl_selfsigned_aliases: []
      ssl_selfsigned_certificate: "{{ playbook_ssl_certificate }}"
      ssl_selfsigned_key: "{{ playbook_ssl_key }}"
      when: playbook_ssl_selfsigned_certs

    - role: httpd
      become: true
      become_user: root
      httpd_server_name: "{{ playbook_front_server_name }}"
      httpd_server_aliases: []
      httpd_application_name: "{{ playbook_application_name }}"
      httpd_documentroot: "{{ playbook_application_path }}/site"
      httpd_ssl_certificate: "{{ playbook_httpd_ssl_certificate }}"
      httpd_ssl_key: "{{ playbook_httpd_ssl_key }}"
      httpd_ssl_cacertificate: "{{ playbook_httpd_ssl_cacertificate }}"
      httpd_context_name: "{{ playbook_context_name }}"
      httpd_ajp_port: "{{ playbook_tomcat_ajp_port }}"

    - role: postgresql_cluster
      become: true
      become_user: root
      postgresql_cluster_clusters:
        - name: application
          path: /data/services/pgsql/9.6/data
          postgresql_version: "9.6"
          port: "{{ playbook_postgresql_port }}"
          databases:
            - name: "{{ playbook_postgresql_database }}"
              owner: "{{ playbook_postgresql_user }}"
              schemas:
                - "{{ playbook_postgresql_user }}"
          users:
            - username: "{{ playbook_postgresql_user }}"
              password: "{{ playbook_postgresql_password }}"
              databases:
                - name: "{{ playbook_postgresql_database }}"
                  privileges: CONNECT,CREATE

    - role: tomcat
      become: true
      become_user: root
      tomcat_version: 9.0.10
      tomcat_checksum: sha512:ecdee920fcb75bf30cd87c350e0732e8fa566911cd16cf2759689edd324ebac911c0d154e79ffc67e948b29eacc49c88dadc5954383d3c4af2fdb952f3d1c371
      tomcat_dest: /data/opt/tomcat-9.0.10
      tomcat_default_user: "{{ playbook_remote_user }}"
      tomcat_default_java_home: "{{ jdks[playbook_java_key].path }}"
      tomcat_timeout_stop: 30s
      tomcat_download_target_path: "{{ playbook_download_target_path }}"
      tomcat_default_extra_opts: "{{ playbook_tomcat_extra_opts }}"
      tomcat_catalina_bases:
        - name: "{{ playbook_application_name }}"
          path: "{{ playbook_application_tomcat_path }}"
          apj_port: "{{ playbook_tomcat_ajp_port }}"
          http_port: "{{ playbook_tomcat_http_port }}"
          ajp_max_threads: "{{ playbook_tomcat_ajp_max_threads }}"
          http_max_threads: "{{ playbook_tomcat_http_max_threads }}"
          shutdown_port: "{{ playbook_tomcat_shutdown_port }}"
